#Config

### Data Generation
#glob path to sensor data, recursive wildcards allowed
rgb_sensor_pool: /orange/ewhite/NeonData/**/Camera/**/*.tif 
HSI_sensor_pool: /orange/ewhite/NeonData/**/Reflectance/*.h5 
CHM_pool: /orange/ewhite/NeonData/**/CanopyHeightModelGtif/*.tif

#NEON data filtering
min_stem_diameter: 10
#Minimum number of samples per class to be included
min_samples: 1
#The proportion of plotIDs to use test
test_fraction: 0.1
#Iterations to search for the best train-test split that mantains the largest number of species. Set to 1 for debugging, no files will be written
iterations: 50
# minimum CHM height, leave blank to skip CHM filtering
min_CHM_height: 1
#Minimum difference between measured height and CHM height
min_CHM_diff: 4
#Directoy to store cropped images from crowns
crop_dir: 
#Pixel size of the crowns. Square crops around each pixel of size x are used
window_size: 11

#Network Parameters
gpus:
workers: 0
batch_size: 64
train:
    crown_dir:
    fast_dev_run: False
    accelerator: ddp
validation:
    crown_dir:
