name: DeepTreeAttention
channels:
  - conda-forge
dependencies:
  - tensorflow
  - sphinx
  - recommonmark
  - pyyaml
  - pytest
  - numpydoc
  - h5py
  - numpy
  - pillow
  - pip
  - matplotlib
  - rasterio
  - sphinx_rtd_theme
  - pandas
  - twine
  - yapf
  - pip:
    - opencv-python
    - sphinx-markdown-tables
    - bumpversion
