train:
    classes: 20
    sensor_path: /orange/ewhite/b.weinstein/Houston2018/2018IEEE_Contest/Phase2/FullHSIDataset/20170218_UH_CASI_S4_NAD83.pix  #path to sensor data
    ground_truth_path: /orange/ewhite/b.weinstein/Houston2018/2018IEEE_Contest/Phase2/TrainingGT/2018_IEEE_GRSS_DFC_GT_TR.tif #path to ground truth class raster
    crop_height: 11
    crop_width: 11
    sensor_channels: 48
    epochs: 1
    learning_rate: .001
    gpu: 0
    batch_size: 10
    steps: None # Mostly for testing purposes, steps = 1 would train on just one batch. Set to None for main environment.

callbacks:
    snapshots_path: /../models/
    project_name: DeepTreeAttention
    
#All the above parameters apply to evaluation except for paths, leave blank to ignore.
#!!!Test data is not yet available, predict itself for the moment to get things running!!!
evaluation:
    sensor_path: /orange/ewhite/b.weinstein/Houston2018/2018IEEE_Contest/Phase2/FullHSIDataset/20170218_UH_CASI_S4_NAD83.pix  #path to sensor data
    ground_truth_path: /orange/ewhite/b.weinstein/Houston2018/2018IEEE_Contest/Phase2/TrainingGT/2018_IEEE_GRSS_DFC_GT_TR.tif #path to ground truth class raster

