callbacks:
    snapshots_path: /../models/
    project_name: DeepTreeAttention

train:
  epochs: 1
  steps_per_epoch: 1 # only honored if trained using keras-sequence generator
  learning_rate: .001
  gpu: 0