#Parallel workers
cpu_workers: 10

train:
    classes: 21
    sensor_path: data/processed/20170218_UH_CASI_S4_NAD83_crop.tif  #path to sensor data
    ground_truth_path: data/raw/2018_IEEE_GRSS_DFC_GT_TR_resampled.tif #path to ground truth class raster
    tfrecords: /orange/ewhite/b.weinstein/Houston2018/tfrecords/train/ # Note this is not under version control, see generate.py to create locally.
    crop_size: 11
    sensor_channels: 48
    epochs: 50
    learning_rate: .001
    gpu: 1
    batch_size: 512
    weighted_sum: False
    # Below are mostly for testing purposes, steps = 1 would train on just one batch. Set to blank for main environment to iterate over full data.
    steps:
    shuffle: True

callbacks:
    snapshots_path: /../models/
    project_name: DeepTreeAttention

#All the above parameters apply to evaluation except for paths, leave blank to ignore.
evaluation:
    tfrecords:
    sensor_path:
    ground_truth_path:
    steps:
    
class_labels:
    0: "Unclassified"
    1 : "Healthy grass"
    2 : "Stressed grass"
    3 : "Artificial turf"
    4 : "Evergreen trees"
    5 : "Deciduous trees"
    6 : "Bare earth"
    7 : "Water"
    8 : "Residential buildings"
    9 : "Non-residential buildings"
    10 : "Roads"
    11 : "Sidewalks"
    12 : "Crosswalks"
    13 : "Major thoroughfares"
    14 : "Highways"
    15 : "Railways"
    16 : "Paved parking lots"
    17 : "Unpaved parking lots"
    18 : "Cars"
    19 : "Trains"
    20 : "Stadium seat"